version: '3.5'

services:
  postgresql:
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      #- ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  nats1:
    image: nats-streaming:linux
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--cluster_name orders --cluster nats://0.0.0.0:4248 --routes nats://nats1:4248 --http_port 8222"
volumes:
  sql:  